### ISSUE TITLE
Redundant React Fragment

### ISSUE THREAD

**Issue by Tsirimaholy** [SignCraft2024/signcraft#15]
on src/App.tsx:11
React fragments are a feature in React that allows you to group multiple elements together without adding an extra DOM element. They are a way to return multiple elements from a component’s render method without requiring a wrapping parent element.
However, a fragment is redundant if it contains only one child, or if it is the child of an HTML element.
```js
<><Foo /></>;    // Noncompliant: The fragment has only one child
<p><>foo</></p>; // Noncompliant: The fragment is the child of the HTML element 'p'
```

**Comment by NiceGuyMe** [comment]
fixed
